language: node_js
node_js:
    - "stable"
    - "4.2"
branches:
    only:
        - master
        - stable
before_script:
    - npm install -g gulp
    - git config --global user.name 'DW via Travis CI'
    - git config --global user.email 'questions@davidwesst.com'
    - sed -i'' "s~git@github.com:davidwesst/dw-www.git~https://${GH_TOKEN}:x-oauth-basic@github.com/davidwesst/dw-www.git~" gulpfile.js
script:
    - gulp build
    - gulp deploy